"""
Tests functions in the conversion.py module.
Fo2 conversions are tested against values generated by
Iacovino, Kayla. (2022). Calculate fO2 Buffer (1.5). Zenodo.
                                             https://doi.org/10.5281/zenodo.7387196
"""

import evo
import evo.conversions as cnvs
import pytest
import numpy as np


def test_fmq2fo2():
    assert cnvs.fmq2fo2(+3.3479, 1473.15, 10, "frost1991") == pytest.approx(
        -4.95224, 0.001
    )


def test_fmq_2iw():
    assert cnvs.fmq_2iw(-3, 1473.15, 10, "frost1991") == pytest.approx(0.6575, 0.001)


def test_fo2_2fmq():
    assert cnvs.fo2_2fmq(-4.95224, 1473.15, 10, "frost1991") == pytest.approx(
        +3.3479, 0.001
    )


def test_fmq():
    assert cnvs.fmq(1473.15, 10, "frost1991") == pytest.approx(-8.3, 0.001)


def test_iw2fo2():
    assert cnvs.iw2fo2(1, 1473.15, 10, "frost1991") == pytest.approx(-10.95, 0.001)


def test_iw_2fmq():
    assert cnvs.iw_2fmq(1, 1473.15, 10, "frost1991") == pytest.approx(-2.6575, 0.001)


def test_fo2_2iw():
    assert cnvs.fo2_2iw(-10.9576, 1473.15, 10, "frost1991") == pytest.approx(1, 0.001)


def test_iw():
    assert cnvs.iw(1473.15, 10, "frost1991") == pytest.approx(-11.9576, 0.001)


def test_nno2fo2():
    assert cnvs.nno2fo2(-1, 1473.15, 10, "frost1991") == pytest.approx(-8.562, 0.001)


def test_fo2_2nno():
    assert cnvs.fo2_2nno(-8.5626, 1473.15, 10, "frost1991") == pytest.approx(-1, 0.001)


def test_nno():
    assert cnvs.nno(1473.15, 10, "frost1991") == pytest.approx(-7.5626, 0.001)


@pytest.mark.parametrize(
    "buffer, result",
    [
        ("FMQ", np.log(10 ** (-8.3))),
        ("IW", np.log(10 ** (-11.9576))),
        ("NNO", np.log(10 ** (-7.5626))),
    ],
)
def test_generate_fo2(buffer, result):
    run = evo.dgs_classes.RunDef()
    run.FMQ_MODEL = "frost1991"
    sys = evo.dgs_classes.ThermoSystem(run)
    sys.T = 1473.15

    assert cnvs.generate_fo2(sys, 0, buffer, 10) == pytest.approx(result, 0.001)


@pytest.mark.parametrize(
    "buffer, expected", [("FMQ", -1.7), ("IW", 1.958), ("NNO", -2.437)]
)
def test_generate_fo2_buffer_buffer_provided(buffer, expected):
    run = evo.dgs_classes.RunDef()
    run.FMQ_MODEL = "frost1991"
    sys = evo.dgs_classes.ThermoSystem(run)
    sys.T = 1473.15

    assert cnvs.generate_fo2_buffer(
        sys, 1e-10, 10, buffer_choice=buffer
    ) == pytest.approx(expected, 0.001)
